export const ui = {
  page: {
    display: "grid",
    gap: "16px",
  },
  eyebrow: {
    margin: 0,
    fontSize: "11px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--ikms-muted)",
    fontWeight: 600,
  },
  pageHeader: {
    display: "grid",
    gap: "8px",
  },
  pageTitle: {
    margin: 0,
    fontSize: "22px",
    lineHeight: 1.3,
    letterSpacing: "-0.01em",
    color: "var(--ikms-text)",
    fontWeight: 600,
  },
  pageDescription: {
    margin: 0,
    color: "var(--ikms-muted)",
    maxWidth: "72ch",
  },
  heroCard: {
    padding: "16px",
    borderRadius: "4px",
    background: "var(--ikms-panel)",
    border: "1px solid var(--ikms-line)",
    boxShadow: "none",
  },
  card: {
    padding: "16px",
    borderRadius: "4px",
    background: "var(--ikms-panel)",
    border: "1px solid var(--ikms-line)",
    boxShadow: "none",
  },
  subCard: {
    padding: "12px",
    borderRadius: "4px",
    background: "var(--ikms-panel-muted)",
    border: "1px solid var(--ikms-line)",
  },
  grid: {
    display: "grid",
    gap: "12px",
  },
  twoColumn: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "12px",
  },
  threeColumn: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "12px",
  },
  toolbar: {
    display: "grid",
    gap: "12px",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    alignItems: "end",
  },
  actionRow: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  field: {
    display: "grid",
    gap: "4px",
  },
  label: {
    fontSize: "12px",
    fontWeight: 600,
    color: "var(--ikms-muted-strong)",
    letterSpacing: "0.01em",
  },
  primaryButton: {
    width: "fit-content",
    padding: "8px 12px",
    borderRadius: "4px",
    border: "1px solid transparent",
    background: "var(--ikms-accent)",
    color: "#FFFFFF",
    fontWeight: 600,
    boxShadow: "none",
    cursor: "pointer",
  },
  secondaryButton: {
    width: "fit-content",
    padding: "8px 12px",
    borderRadius: "4px",
    border: "1px solid var(--ikms-line-strong)",
    background: "var(--ikms-panel)",
    color: "var(--ikms-text)",
    fontWeight: 600,
    cursor: "pointer",
  },
  dangerButton: {
    width: "fit-content",
    padding: "8px 12px",
    borderRadius: "4px",
    border: "1px solid transparent",
    background: "var(--ikms-danger)",
    color: "#FFFFFF",
    fontWeight: 600,
    cursor: "pointer",
  },
  metricRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: "12px",
  },
  metricCard: {
    display: "grid",
    gap: "4px",
    padding: "12px",
    borderRadius: "4px",
    background: "var(--ikms-panel-muted)",
    border: "1px solid var(--ikms-line)",
  },
  statusBadge: {
    display: "inline-flex",
    width: "fit-content",
    alignItems: "center",
    gap: "4px",
    padding: "2px 8px",
    borderRadius: "999px",
    background: "var(--ikms-accent-soft)",
    border: "1px solid var(--ikms-line)",
    color: "var(--ikms-muted-strong)",
    fontSize: "11px",
    fontWeight: 600,
  },
} as const;
