export const ui = {
  page: {
    display: "grid",
    gap: "1.5rem",
  },
  eyebrow: {
    margin: 0,
    fontSize: "0.78rem",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--muted)",
    fontWeight: 700,
  },
  pageHeader: {
    display: "grid",
    gap: "0.5rem",
  },
  pageTitle: {
    margin: 0,
    fontSize: "2rem",
    lineHeight: 1.1,
    letterSpacing: "-0.03em",
    color: "var(--text)",
  },
  pageDescription: {
    margin: 0,
    color: "var(--muted)",
    maxWidth: "72ch",
  },
  heroCard: {
    padding: "1.4rem 1.5rem",
    borderRadius: "1.3rem",
    background: "linear-gradient(180deg, rgba(255,255,255,0.94) 0%, rgba(246,249,252,0.94) 100%)",
    border: "1px solid var(--line)",
    boxShadow: "var(--shadow)",
  },
  card: {
    padding: "1.15rem",
    borderRadius: "1.15rem",
    background: "var(--panel)",
    border: "1px solid var(--line)",
    boxShadow: "0 10px 28px rgba(15, 23, 40, 0.04)",
  },
  subCard: {
    padding: "0.9rem 1rem",
    borderRadius: "0.95rem",
    background: "var(--panel-muted)",
    border: "1px solid rgba(191, 208, 226, 0.7)",
  },
  grid: {
    display: "grid",
    gap: "1rem",
  },
  twoColumn: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "1rem",
  },
  threeColumn: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "1rem",
  },
  toolbar: {
    display: "grid",
    gap: "0.75rem",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    alignItems: "end",
  },
  actionRow: {
    display: "flex",
    gap: "0.65rem",
    flexWrap: "wrap",
    alignItems: "center",
  },
  field: {
    display: "grid",
    gap: "0.45rem",
  },
  label: {
    fontSize: "0.82rem",
    fontWeight: 700,
    color: "var(--muted-strong)",
    letterSpacing: "0.01em",
  },
  primaryButton: {
    width: "fit-content",
    padding: "0.78rem 1.05rem",
    borderRadius: "0.85rem",
    border: "none",
    background: "linear-gradient(180deg, var(--accent) 0%, var(--accent-strong) 100%)",
    color: "#f8fbff",
    fontWeight: 700,
    boxShadow: "0 10px 18px rgba(11, 99, 206, 0.18)",
    cursor: "pointer",
  },
  secondaryButton: {
    width: "fit-content",
    padding: "0.78rem 1.05rem",
    borderRadius: "0.85rem",
    border: "1px solid var(--line-strong)",
    background: "var(--panel-solid)",
    color: "var(--text)",
    fontWeight: 700,
    cursor: "pointer",
  },
  dangerButton: {
    width: "fit-content",
    padding: "0.78rem 1.05rem",
    borderRadius: "0.85rem",
    border: "none",
    background: "linear-gradient(180deg, #d64232 0%, var(--danger) 100%)",
    color: "#fff8f7",
    fontWeight: 700,
    cursor: "pointer",
  },
  metricRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: "0.85rem",
  },
  metricCard: {
    display: "grid",
    gap: "0.3rem",
    padding: "0.95rem 1rem",
    borderRadius: "1rem",
    background: "var(--panel-muted)",
    border: "1px solid rgba(191, 208, 226, 0.7)",
  },
  statusBadge: {
    display: "inline-flex",
    width: "fit-content",
    alignItems: "center",
    gap: "0.35rem",
    padding: "0.28rem 0.55rem",
    borderRadius: "999px",
    background: "#edf4fb",
    border: "1px solid var(--line)",
    color: "var(--muted-strong)",
    fontSize: "0.78rem",
    fontWeight: 700,
  },
} as const;
