package com.ikms.review;

public enum ReviewQueueReason {
  UNLINKED,
  LOW_CLIENT_CONFIDENCE,
  LOW_CLASSIFICATION_CONFIDENCE,
  LOW_EXTRACTION_CONFIDENCE,
  DUPLICATE_UNCERTAINTY,
  REDACTION_FAILED,
  PROMPT_INJECTION_RISK,
  PROCESSING_FAILED
}
