package com.ikms.document;

public enum DocumentProcessingStage {
  QUEUED,
  VIRUS_SCAN,
  OCR_TEXT_EXTRACTION,
  LANGUAGE_DETECTION,
  DOCUMENT_CLASSIFICATION,
  METADATA_EXTRACTION,
  BUSINESS_REFERENCE_EXTRACTION,
  CONFIDENCE_CALCULATION,
  VALIDATION,
  REVIEW_QUEUE,
  REVIEW_CORRECTION,
  APPROVAL,
  VERSION_CREATION,
  KNOWLEDGE_PROJECTION,
  TIMELINE_UPDATE,
  RETRIEVAL_READY,
  FAILED
}
