package com.ikms.security.domain;

public enum Permission {
  CLIENT_VIEW,
  REVIEW_QUEUE_ACCESS,
  INTAKE_ACCESS,
  SEARCH_CLIENT_KNOWLEDGE,
  ASK_CLIENT_AI,
  VIEW_REDACTED_DOCUMENTS,
  VIEW_ORIGINAL_DOCUMENTS,
  VIEW_PII,
  VIEW_AUDIT,
  EXPORT_AUDIT,
  MANAGE_CONFIGURATION,
  MANAGE_USERS
}
